#!/Users/han/miniconda3/bin/python
import sys
import os

# Add the current directory to sys.path so app can be imported
sys.path.append(os.path.join(os.path.dirname(__file__)))

from app.cli import app

if __name__ == "__main__":
    app()
